### ISSUE TITLE
typos & placeholder copy on settings page.

### ISSUE THREAD

**Issue by desertrat10** [unlock-protocol/unlock-wordpress-plugin#35]
I've attached screenshots of the two issues on the settings page under the Networks tab. 
<img width="1349" alt="Screen Shot 2021-12-22 at 8 49 39 PM" src="https://user-images.githubusercontent.com/19274187/147270132-57aa1224-91c2-46af-88cf-cda168953604.png">
<img width="1337" alt="Screen Shot 2021-12-22 at 9 07 31 PM" src="https://user-images.githubusercontent.com/19274187/147270154-51886e7a-6ac6-4298-9556-ffb861aa0af1.png">

**Comment by julien51** [comment]
Fixed!
