### ISSUE TITLE
Enable paywall configuration

### ISSUE THREAD

**Issue by keyeightysix** [unlock-protocol/unlock-wordpress-plugin#36]
https://docs.unlock-protocol.com/developers/paywall/configuring-checkout

Would be great to be able to configure the json sent. Could be just essentials for UX

Even if messageToSign was the only param for now.

This does also give me the idea that meta inputs could be included here. That then leads on to the idea that members could have it's own post type and we could be keeping a record in WP for each interaction a user has with Unlock and saving additional meta inputs to this post type upon interaction.

This gives the WP site owner a great deal of power to utilize their Unlock member data throughout their site and for marketing efforts.

**Comment by julien51** [comment]
This is a great idea. There are a lot of things that could be configured "manually" by supplying a JSON blob as "override"?

Our goal with the plugin was to start with something "basic" and add functionality as we grow.

**Comment by julien51** [comment]
Fixed in #47
