### ISSUE TITLE
The Current Unlock Protocol WP Plugin Repository Needs Total Overhaul

### ISSUE THREAD

**Issue by SolomonFoskaay** [unlock-protocol/unlock-wordpress-plugin#61]
After dedicating a lot of hours in the last 1 week+ to understand and start attempting to fix some issues in this Unlock wp plugin repo, I spent a lot of those time on replicating a working dev environment for the current unlock plugin repo using Lando as it is now but couldn't have the Lando setup working fine eventually.

So, I decided to use my own wp local dev setup which is far simpler and up to date with wp itself and allowed me to use the plugin while developing just like users will eventually use it on real live wp website setup.

Thus, I recommend an overhauling of this current unlock wp plugin repo as it is to something much simpler.
Some of the present and future benefits of doing that are:

**(1)** It becomes easier for future wp plugin dev contributors to handle on easy to set-up local wp dev environment compared to this current complicated Lando setup

**(2)** The repo becomes a directly usable wp plugin as is. 

Currently if user download the Unlock Protocol wp plugin zip and attempt to upload and use it directly on Wordpress. it shows up but activating it send the wp website into critical error due to other conflicting files used for development via Lando and co.

Instead, with the new overhaul suggestion, user can download the zip file of the Unlock wp plugin repo, upload to their wp website and be able to use it as is without breaking their website.

**(3)** It could become a testing ground for both user and dev contributor to have access to latest version of the plugin for beta-testing before finally been released to the official wp plugins repo. Since they can just download the zip version and use it on their wp website without the need to remove or edit any file in there.

**(4)** This will also enhance the ease of detecting any vulnerability or issues that need fixing in the Unlock wp plugin

**(5)** Shipping fixes of issues raised to the Unlock wp plugin becomes much easier for present and future developers contributing to this plugin repo

**Comment by SolomonFoskaay** [comment]
@julien51 am interested in helping work on fixing this issue and will need 2 things done to move ahead asap:

(1) Optional: Kindly create a new branch to back up the current repo as is in case needed for references in future because after the overhaul the structure will change and follow the same structure as the current released version of the plugin for users.

(2) What is the bounty price attached to fix this issue?

Thanks!

**Comment by julien51** [comment]
Fully agreed! Let me work on this soon!

**Comment by SolomonFoskaay** [comment]
@julien51 Though you said you will handle this issue yourself but am considering you have a lot at hand already and doing this might take a long time. 
Without the repo overhaul done first, it is hard to contribute further to it. Thus, I have decided to help get the overhaul done faster with this pull request pushed ***[SolomonFoskaay-UPWpPluginFixes002-Repo-Overhaul](https://github.com/unlock-protocol/unlock-wordpress-plugin/pull/62)*** for you to check.

Kindly do let me know if there are any additional changes to do to have PR merged so we can move on to other issues like the plugin security and other fixes.

# Fixes for Issue #61  Done
I have fixed the issues raised to overhaul the Unock Protocol Wordpress Plugin Repository from what it is now using Lando local development environment (which requires complex wp local dev setup by developers) to a much easier-to-manage version for contributing devs.

The following was done:

1. The overhaul of the unlock wp repo (removed Lando-related files and folders, then fix repo to march file structure of the current Version 3.2.3 released on the wp official plugin repo)

2. Added README.md and fixed README.txt + deleted phpcs.xml file

3. Updated README.md and fixed README.txt to be more readable and added a guide for the wp local dev environment setup for future contributing developers.

4. Added a visual indicator for users to differentiate the officially released version and the developer's version downloaded as a zip file directly from the GitHub repo. This will also surely make it easier for developers to switch between the two for proper testing during development. See Screenshot attached below:

![UnlockProtocol-Wordpress-Plugin-Img001a-Dev-and-User-Version-in-Wp-Admin](https://user-images.githubusercontent.com/83863629/221135327-bd8a6a2c-87b5-4a44-b2eb-4eeba5b42a7e.png)

**Comment by julien51** [comment]
> Without the repo overhaul done first, it is hard to contribute further to it. Thus, I have decided to help get the overhaul done faster with this pull request pushed https://github.com/unlock-protocol/unlock-wordpress-plugin/pull/62 for you to check.

Amazing! Let me check this today!

**Comment by julien51** [comment]
Ok so I think there is some good and some that can be improved!
I like the idea of having 2 versions (the dev + the prod one), and I like the lando cleanup.
However, I think we still need to have a better way of "building" the plugin rather than have everything be changed from the `build` subdirectory.

Let me try to open another PR.

I will contact you regarding bounties :)

**Comment by SolomonFoskaay** [comment]
> Ok so I think there is some good and some that can be improved! I like the idea of having 2 versions (the dev + the prod one), and I like the lando cleanup. However, I think we still need to have a better way of "building" the plugin rather than have everything be changed from the `build` subdirectory.
> 
> Let me try to open another PR.
> 
> I will contact you regarding bounties :)

@julien51 I think for clarity, I may need to do a video about how developers can download the zip,
add it to localwp,
edit the plugin files to add any feature,
push it directly from localwp to the github
and finally, push a PR.
Then we can add it as part of README.md under the local development guide.

**Comment by julien51** [comment]
That is a great idea @SolomonFoskaay ! What about a $50 bounty for such a video?
Also please check https://github.com/unlock-protocol/unlock-wordpress-plugin/pull/64 and let me know what you think!

**Comment by julien51** [comment]
It is still misisng a few things like the "dev" name to avoid conflicts but I think that's a start!

**Comment by SolomonFoskaay** [comment]
> That is a great idea @SolomonFoskaay ! What about a $50 bounty for such a video? Also please check #64 and let me know what you think!

Please, let's do $100 for the video (will be well-detailed). 
I will do the video early tomorrow morning. 
Will first send you via Google drive, so you can upload on the Unlock YT and I can later embed it in README.md with a PR.

I have checked #64 . I think you need to publish it first as am not able to see the full structure very well.

For example, you added some guide which relate to SVN, I believe that is for the person which have access to upload to the official wp plugin repo. Every other devs contributing don't have access or do you intend to release the access.

So, am thinking we divide this into two and sort them one by one:
(1) The contributing devs' version: 
Version for those devs who don't have access to build the final plugin for official wp repo upload (this works with the localwp devs - like I said will use the previous structure I sent to do the video and send it for you to understand it better).
This may be the main repo structure.

(2) The actual wp svn build version:
This should be taking the main repo in (1) above and putting it together for Wordpress official svn deployment which for sure will have a bit different structure than the actual main repo contributing devs contribute their features to.

For example, If we follow the structure I sent earlier in pull request #62  . Once published. You can then add a `build` folder to it. For the build folder, you will be the one to work on structuring it as needed because you are currently the main access to deploying the build to the official wp svn repo.
That means contributing devs like myself and others can add features, we test and all confirm it works. You then use the code to update the build version inside the build folder to be pushed to svn wp repo.

I think that makes things much clearer.

But using the svn structure with the actual repo for contributing devs may make things break when used on localwp IMO.

**Comment by SolomonFoskaay** [comment]
> Ok so I think there is some good and some that can be improved! I like the idea of having 2 versions (the dev + the prod one), and I like the lando cleanup. However, I think we still need to have a better way of "building" the plugin rather than have everything be changed from the `build` subdirectory.
> 
> Let me try to open another PR.
> 
> I will contact you regarding bounties :)

I already responds to this under the 

> It is still misisng a few things like the "dev" name to avoid conflicts but I think that's a start!

Are you referring to the #62 or #64 here, please?

**Comment by SolomonFoskaay** [comment]
@julien51 Here is the detailed video on how the #62  repo structure will make it easier for contributing devs to add new features or fix existing issues in the Unlock wp plugin.

Kindly watch it a-z to understand in detail and let me know if you got any unanswered questions in there.

Also, when we finally have the repo structure in place, `might do another video` that will then use the repo as sample to guide devs that will be contributing to the wp plugin repo step by step on using localwwp to add features/fix issues in the plugin without settingup complicated locwl wp dev environment at all.

https://drive.google.com/file/d/1gdW-cfTckBX-UZDa5fbgsP5A_vwUhMpv/view?usp=share_link

**Comment by SolomonFoskaay** [comment]
@julien51 Here is the detailed video on how the #62  repo structure will make it easier for contributing devs to add new features or fix existing issues in the Unlock wp plugin.

Kindly watch it a-z to understand in detail and let me know if you got any unanswered questions in there.

Also, when we finally have the repo structure in place, `might do another video` that will then use the repo as sample to guide devs that will be contributing to the wp plugin repo step by step on using localwwp to add features/fix issues in the plugin without settingup complicated locwl wp dev environment at all.

https://drive.google.com/file/d/1gdW-cfTckBX-UZDa5fbgsP5A_vwUhMpv/view?usp=share_link

**Comment by julien51** [comment]
Lets close this fior now as we have made progress.
